### ISSUE TITLE
Create a default configuration file when program is first used

### ISSUE THREAD

**Issue by rossboswell** [kvannotten/pcd#2]
**Is your feature request related to a problem? Please describe.**
For usability reasons, I think it'll be nice if the user does not need to create a file themselves. Currently if a new user wants to use this, they'd have to copy and paste the dummy configuration file from the  README.md.

**Describe the solution you'd like**
If a configuration file does not exist, create a dummy one. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kvannotten** [comment]
That's a good idea. How would you see it? At first usage we just create a default, dummy file? Another option would be to go through a wizard like adding of podcasts.
I think I would prefer the former.

**Comment by rossboswell** [comment]
Maybe a default file that contains one or two of the most popular podcasts. At least a file that allows the user to use the program straight away.

On an unrelated note, perhaps I should create a new issue for this, it might be nice to have a add/remove feature within the program.

**Comment by kvannotten** [comment]
Yup something like that! Upon first run we'd create a file, notifying the user that we've done so and directing them to modify that file.

Indeed, you can make a new issue for that

**Comment by kvannotten** [comment]
Closed in error

**Comment by kvannotten** [comment]
After thinking about it for a while (a long while apparently :P) I decided against automatically creating a configuration file. I think it's not worth it in the end. I did make it so that it gives some information to the user on how to create the configuration file (see 0c51783), because your point remains valid! It's just that I feel weird to automatically add config files into users' home folders.
