### ISSUE TITLE
Download a range of episodes for a podcast

### ISSUE THREAD

**Issue by gcantieni** [kvannotten/pcd#20]
**Is your feature request related to a problem? Please describe.**
I'd like the ability to download a range of episodes to a podcast

**Describe the solution you'd like**
`pcd d podcast-name 63-65` which would download 63, 64, and 65. It would also be nice to have a syntax for doing combinations of ranges and individual episodes. For example:

`pcd d podcast-name 63-65,67,69-75` 

would download 63, 64, 65, 67, 69, 70, 71, 72, 73, 74, 75. 

**Describe alternatives you've considered**
Manually writing a function to call pcd for 63-65. This seems cumbersome, however.

**Additional context**
One of the reasons I would prefer a command line podcast client is for the ability to do things in bulk

**Comment by kvannotten** [comment]
That's actually a really interesting idea. I'm gonna check how easy it would be to parse ranges and how extensive that syntax could/should be.

Something like you suggest: `63-65` is straight forward, but perhaps stuff like `63-67,!64` would be interesting to have too.

**Comment by gcantieni** [comment]
Cool! I agree that the `63-67,!64` would be trickier, I think they have this in `greg` so looking at the greg parsing code might help?
I'd also be happy to contribute. I've done a bit in go though it's been a while.

**Comment by kvannotten** [comment]
I'd love for you to have a look at it.

Let me know if you have any questions.

**Comment by johnelliott** [comment]
@gcantieni I also wanted this feature too, but then I first used the seq and parallel programs. It's a very unix-y solution, but it turns out ids being integers is great. You may need to install and play with seq and parallel a bit, but this works for me:

episode downloads, remove the word echo to make it live:
```
$ seq 4 10 |parallel echo pcd download mypodcast {}
pcd download mypodcast 4
pcd download mypodcast 5
pcd download mypodcast 6
pcd download mypodcast 7
pcd download mypodcast 8
pcd download mypodcast 9
pcd download mypodcast 10
```

You can get creative with cron, more here <https://gist.github.com/johnelliott/c1cd2f37d4a9de8b58a50d6f04e53d4e>

Thanks for making the tool @kvannotten, I'm really using it to stay sane and informed during the pandemic.

**Comment by dstpierre** [comment]
@gcantieni @kvannotten is it still available, I'd be interested in taking this one as well.

Let me know if the feature is still avail for PR.

Thanks

**Comment by kvannotten** [comment]
hey @dstpierre it's still available, feel free to tackle it!
